config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :comments
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    collection do
      get :myrecipe
      get :searchcuisine
      get :search
  end
  end 
  resources :cuisines
  resources :contacts
  get 'statistics/index'
  get 'site/index'
  get 'site/about', to: 'site#about'
  devise_for :users
  resources :users
  resources :cookcategories
  resources :roles

  root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      # can :update, Auth, [:isbanned]
      # cannot :update, Auth, [:email, ], :auth_id != auth.id

    elsif user.member?
      can :show, User
      can :read, Cookcategory
      can :create, Contact
      can :update, User do |u|
        u.try(:id) == user.id
      end
      can :create, Comment
      can :read, Recipe
      can :myrecipe, Recipe
      can :search, Recipe
      can :searchcuisine, Recipe
      can :destroy, Recipe do |u|
        u.try(:user_id) == user.id
      end
      can :update, Recipe do |u|
          u.try(:user_id) == user.id
      end
      can :create, Recipe
    else
      can :read, Cookcategory
      can :create, Contact
      can :show, Recipe
      can :read, Recipe
      can :search, Recipe
      can :searchcuisine, Recipe
    end
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/cookcategory.rb
class Cookcategory < ActiveRecord::Base
  has_many :users
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
  accepts_nested_attributes_for :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipes, :through => :ingredient_recipes
  has_many :ingredient_recipes, dependent: :destroy
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  attr_accessor :amount
  attr_accessor :measurement_unit #-> need a setter/getter

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :cuisine
  belongs_to :cookcategory
  belongs_to :user
  has_many :ingredients, :through => :ingredient_recipes
  has_many :ingredient_recipes, dependent: :destroy

  has_many :comments, dependent: :destroy
  #accepts_nested_attributes_for :ingredient_recipes
  ratyrate_rateable 'recipe'
  mount_uploader :picture, RecipeUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  belongs_to :cookcategory
  before_save :assign_role

  has_many :comments, dependent: :destroy

  validates_presence_of(:username)
  mount_uploader :picture, ProfilepicUploader

  ratyrate_rater

  def assign_role
    self.role = Role.find_by_name("Member") if self.role.nil?
  end

  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end
  def member?
    self.role.name == "Member" if !self.role.blank?
  end
end

app/controllers/cookcategories_controller.rb
class CookcategoriesController < ApplicationController
  before_action :set_cookcategory, only: [:show, :edit, :update, :destroy]
 load_and_authorize_resource
  # GET /cookcategories
  # GET /cookcategories.json
  def index
    @cookcategories = Cookcategory.all
  end

  # GET /cookcategories/1
  # GET /cookcategories/1.json
  def show
  end

  # GET /cookcategories/new
  def new
    @cookcategory = Cookcategory.new
  end

  # GET /cookcategories/1/edit
  def edit
  end

  # POST /cookcategories
  # POST /cookcategories.json
  def create
    @cookcategory = Cookcategory.new(cookcategory_params)

    respond_to do |format|
      if @cookcategory.save
        format.html { redirect_to @cookcategory, notice: 'Cookcategory was successfully created.' }
        format.json { render :show, status: :created, location: @cookcategory }
      else
        format.html { render :new }
        format.json { render json: @cookcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookcategories/1
  # PATCH/PUT /cookcategories/1.json
  def update
    respond_to do |format|
      if @cookcategory.update(cookcategory_params)
        format.html { redirect_to @cookcategory, notice: 'Cookcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @cookcategory }
      else
        format.html { render :edit }
        format.json { render json: @cookcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookcategories/1
  # DELETE /cookcategories/1.json
  def destroy
    @cookcategory.destroy
    respond_to do |format|
      format.html { redirect_to cookcategories_url, notice: 'Cookcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookcategory
      @cookcategory = Cookcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookcategory_params
      params.require(:cookcategory).permit(:name)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cookcategories_helper.rb
module CookcategoriesHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cookcategories/_form.html.erb
<%= form_for(@cookcategory) do |f| %>
  <% if @cookcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookcategory.errors.count, "error") %> prohibited this cookcategory from being saved:</h2>

      <ul>
      <% @cookcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= f.text_field :name, :placeholder => "Name"%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookcategories/edit.html.erb
<body id="pageBody">
<div class="container">
  <div class="divPanel page-content">

    <div class="row-fluid">

      <div class="span12" id="divMain">

      <h1>Editing Cookcategory</h1>

          <%= render 'form' %>

          <%= link_to 'Show', @cookcategory %>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/cookcategories/index.html.erb
<body id="pageBody">
<div class="container">
  <div class="divPanel page-content">

    <div class="row-fluid">

      <div class="span12" id="divMain">

      <p id="notice"><%= notice %></p>

          <h1>Listing Cookcategories</h1>

          <table class="table">
            <thead>
            <tr>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @cookcategories.each do |cookcategory| %>
                <tr>
                  <td><%= cookcategory.name %></td>
                  <td><%= link_to 'Show', cookcategory %></td>
                  <td><%= link_to 'Edit', edit_cookcategory_path(cookcategory) %></td>
                  <td><%= link_to 'Destroy', cookcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>

          <br>

          <%= link_to 'New Cookcategory', new_cookcategory_path %>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/cookcategories/new.html.erb
<body id="pageBody">
<div class="container">
  <div class="divPanel page-content">

    <div class="row-fluid">

      <div class="span12" id="divMain">

      <h1>New Cookcategory</h1>

          <%= render 'form' %>

          <%= link_to 'Back', cookcategories_path %>
      </div>
    </div>
  </div>
</div>
</body>

app/views/cookcategories/show.html.erb
<body id="pageBody">
<div class="container">
  <div class="divPanel page-content">

    <div class="row-fluid">

      <div class="span12" id="divMain">

      <p id="notice"><%= notice %></p>

          <p>
            <strong>Name:</strong>
            <%= @cookcategory.name %>
          </p>

          <%= link_to 'Edit', edit_cookcategory_path(@cookcategory) %> |
          <%= link_to 'Back', cookcategories_path %>

      </div>
    </div>
  </div>
</div>
</body>