config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :comments
  post '/rate' => 'rater#create', :as => 'rate'
  resources :recipes do
    collection do
      get :myrecipe
      get :searchcuisine
      get :search
  end
  end 
  resources :cuisines
  resources :contacts
  get 'statistics/index'
  get 'site/index'
  get 'site/about', to: 'site#about'
  devise_for :users
  resources :users
  resources :cookcategories
  resources :roles

  root 'site#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
      # can :update, Auth, [:isbanned]
      # cannot :update, Auth, [:email, ], :auth_id != auth.id

    elsif user.member?
      can :show, User
      can :read, Cookcategory
      can :create, Contact
      can :update, User do |u|
        u.try(:id) == user.id
      end
      can :create, Comment
      can :read, Recipe
      can :myrecipe, Recipe
      can :search, Recipe
      can :searchcuisine, Recipe
      can :destroy, Recipe do |u|
        u.try(:user_id) == user.id
      end
      can :update, Recipe do |u|
          u.try(:user_id) == user.id
      end
      can :create, Recipe
    else
      can :read, Cookcategory
      can :create, Contact
      can :show, Recipe
      can :read, Recipe
      can :search, Recipe
      can :searchcuisine, Recipe
    end
  end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :recipe
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/cookcategory.rb
class Cookcategory < ActiveRecord::Base
  has_many :users
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_many :recipes
  accepts_nested_attributes_for :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :recipes, :through => :ingredient_recipes
  has_many :ingredient_recipes, dependent: :destroy
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :cuisine
  belongs_to :cookcategory
  belongs_to :user
  has_many :ingredients, :through => :ingredient_recipes
  has_many :ingredient_recipes, dependent: :destroy

  has_many :comments, dependent: :destroy
  #accepts_nested_attributes_for :ingredient_recipes
  ratyrate_rateable 'recipe'
  mount_uploader :picture, RecipeUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  belongs_to :cookcategory
  before_save :assign_role

  has_many :comments, dependent: :destroy

  validates_presence_of(:username)
  mount_uploader :picture, ProfilepicUploader

  ratyrate_rater

  def assign_role
    self.role = Role.find_by_name("Member") if self.role.nil?
  end

  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end
  def member?
    self.role.name == "Member" if !self.role.blank?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Khaiye Khabo</title>
        <link rel="shortcut icon" href="/favicon.ico">
	

<%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  
  <%= csrf_meta_tags %>
  <link href="/assets/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/bootstrap-responsive.min.css" rel="stylesheet">

  <!-- Icons -->
  <link href="/assets/general_foundicons.css" rel="stylesheet" />
  <link href="/assets/social_foundicons.css" rel="stylesheet" type="text/css" />

  <link rel="stylesheet" href="/assets/font-awesome.min.css">

  <link href="/assets/style.css" rel="stylesheet" type="text/css" />
  <link href="/assets/camera.css" rel="stylesheet" type="text/css" />

  <link href="http://fonts.googleapis.com/css?family=Allura" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Aldrich" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Palatino+Linotype" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Calligraffitti" rel="stylesheet" type="text/css">

  <link href="/assets/custom.css" rel="stylesheet" type="text/css" />
  <script src="/assets/jquery.min.js" type="text/javascript"></script>
  <script src="/assets/bootstrap.min.js" type="text/javascript"></script>
  <script src="/assets/default.js" type="text/javascript"></script>


  <script src="/assets/jquery.carouFredSel-6.2.0-packed.js" type="text/javascript"></script>
<script src="/assets/camera.min.js" type="text/javascript"></script>
  <script src="//assets/jquery.easing.1.3.js" type="text/javascript"></script>
  <script type="text/javascript">function startCamera() {$('#camera_wrap').camera({ fx: 'scrollLeft', time: 2000, loader: 'none', playPause: false, navigation: true, height: '65%', pagination: true });}$(function(){startCamera()});</script>

<script src="/assets/jquery.wookmark.js" type="text/javascript"></script>

<script type="text/javascript">$(window).load(function () {var options = {autoResize: true,container: $('#gridArea'),offset: 10};var handler = $('#tiles li');handler.wookmark(options);$('#tiles li').each(function () { var imgm = 0; if($(this).find('img').length>0)imgm=parseInt($(this).find('img').not('p img').css('margin-bottom')); var newHeight = $(this).find('img').height() + imgm + $(this).find('div').height() + $(this).find('h4').height() + $(this).find('p').not('blockquote p').height() + $(this).find('iframe').height() + $(this).find('blockquote').height() + 5;if($(this).find('iframe').height()) newHeight = newHeight+15;$(this).css('height', newHeight + 'px');});handler.wookmark(options);handler.wookmark(options);});</script><script src="/assets/jquery.prettyPhoto.js" type="text/javascript"></script><script type="text/javascript">$("a[rel^='prettyPhoto']").prettyPhoto({social_tools: false});$("a[rel^='prettyPhoto'] img").hover(function(){$(this).animate({opacity:0.7},300)},function(){$(this).animate({opacity:1},300)});</script>


<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "jquery.raty.js" %>
<%= javascript_include_tag "ratyrate.js" %>
</head>


<body id="pageBody">

<div class="container">
<% if alert!=nil %>
    <p class="alert" style="background-color:transparent"><%= alert %></p>
<% end %>
<% if notice!=nil %>
    <p id="notice" style="background-color:transparent"><%= notice %></p>
<%end%>
  <% if flash[:error] %>
    <div id="error" style="color: #b94a48;">
      <%= flash[:error] %>
    </div>
<% end %>
</div>

<div id="decorative2">
  <div class="container">
    <div class="divPanel topArea notop nobottom">
      <div class="row-fluid">
        <div class="span12">

          <div id="divLogo" class="pull-left">
            <a id="divSiteTitle">Khaiye Khabo</a><br />
            <a id="divTagLine">A trusted recipe provider</a>
          </div>

          <div id="divMenuRight" class="pull-right">
            <div class="navbar">
              <button type="button" class="btn btn-navbar-highlight btn-large btn-primary" data-toggle="collapse" data-target=".nav-collapse">
                NAVIGATION <span class="icon-chevron-down icon-white"></span>
              </button>
              <div class="nav-collapse collapse">
                <ul class="nav nav-pills ddmenu dropdown d1">

                  <li class="dropdown"><%= link_to "Home", site_index_path %></li>
                  <% if user_signed_in? %>
                  <li class="dropdown"><a>Recipes<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><%= link_to "Upload a Recipe", new_recipe_path %></li>
                          <li><%= link_to "My Recipes", myrecipe_recipes_path %></li>
                      <li><%= link_to "View Recipes", recipes_path %></li>
                    </ul>
                  </li>
                      <% else %>
                      <li class="dropdown"><%= link_to "View Recipes", recipes_path %></li>
                  <%end%>


                  <% if user_signed_in? %>
                      <% if current_user.role == Role.find_by_name("Admin") %>
                          <li class="dropdown">
                            <a  class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "My Profile", user_path(current_user.id) %>
                              <li><%= link_to "Edit Account Settings", edit_user_registration_path %></li>
                              <li><%= link_to "Edit Personal Settings", edit_user_path(current_user.id)%></li>
                              <li class="dropdown">
                                <a class="dropdown-toggle">Admin Privileges &nbsp;&raquo;</a>
                                <ul class="dropdown-menu sub-menu">
                                  <li><%= link_to "Member Profiles", users_path %></li>
                                  <li><%= link_to "Statistics", statistics_index_path %></li>
                                </ul>
                              </li>
                              <li class="dropdown"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                            </ul>
                          </li>
                          <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Khaiye Khabo<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "About", site_about_path %></li>
                              <li><%= link_to "View Suggestions", contacts_path %></li>
                            </ul>
                          </li>

                      <% elsif current_user.role == Role.find_by_name("Member") %>
                          <li class="dropdown">
                            <a  class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "My Profile", user_path(current_user.id) %>
                              <li><%= link_to "Edit Account Settings", edit_user_registration_path %></li>
                              <li><%= link_to "Edit Personal Settings", edit_user_path(current_user.id)%></li>
                              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                            </ul>
                          </li>
                          <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown">Khaiye Khabo<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to "About", site_about_path %></li>
                              <li><%= link_to "Contact", new_contact_path%></li>
                            </ul>
                          </li>
                      <% end %>

                  <% else %>
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Khaiye Khabo<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "About", site_about_path %></li>
                          <li><%= link_to "Contact", new_contact_path %></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">Sign up/Sign in<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Sign up", new_user_registration_path %></li>
                          <li><%= link_to "Sign in", new_user_session_path %></li>
                        </ul>
                      </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div id="footerInnerSeparator"></div>
  </div>

</div>

<%= yield %>



<div id="footerOuterSeparator"></div>

<div id="divFooter" class="footerArea">

  <div class="container">

    <div class="divPanel">

      <div class="row-fluid">
        <div class="span3" id="footerArea1">

          <h3>About Khaiyekhabo</h3>

          <p>A remarkable source for all south-asian recipes. We’re dedicated to giving you the very best of the south-asian taste, with a focus on dependability, customer service and uniqueness..</p>

          <p>
            <a href="#" title="Terms of Use">Terms of Use</a><br />
            <a href="#" title="Privacy Policy">Privacy Policy</a><br />
          </p>

        </div>
        <div class="span3" id="footerArea2">

          <h3>Problem Sets</h3>
          <p>
            <a href="http://web4.cs.ait.ac.th/projectdemo/projects" title="">Problem Set Solutions</a><br />
            </p>
         

        </div>
        
        <div class="span3" id="footerArea4">

          <h3>Get in Touch</h3>

          <ul id="contact-info">
            <li>
              <i class="general foundicon-phone icon"></i>
              <span class="field">Phone:</span>
              <br />
              (123) 456 7890 / 456 7891
            </li>
            <li>
              <i class="general foundicon-mail icon"></i>
              <span class="field">Email:</span>
              <br />
              <a href="mailto:info@yourdomain.com" title="Email">khaiyekhabo@gmail.com</a>
            </li>
            <li>
              <i class="general foundicon-home icon" style="margin-bottom:50px"></i>
              <span class="field">Address:</span>
              <br />
              Asian Institute of Technology<br />
              Pathumthani, Rangsit<br />
              Thailand
            </li>
          </ul>

        </div>
      </div>

      <br /><br />
      <div class="row-fluid">
        <div class="span12">
          <p class="copyright">
            Copyright © 2015 Khaiyekhabo. All Rights Reserved.
          </p>

          <p class="social_bookmarks">
            <a href="www.facebook.com/khaiyekhabo"><i class="social foundicon-facebook"></i> Facebook</a>
            <a href="www.twitter.com/khaiyekhabo"><i class="social foundicon-twitter"></i> Twitter</a>
          </p>
        </div>
      </div>
      <br />

    </div>

  </div>

</div>


</body>
</html>